# Generated by Django 5.2.7 on 2025-11-03 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeBankSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knows_timebank', models.CharField(choices=[('yes', '예'), ('no', '아니오')], max_length=3, verbose_name='시간은행 인지 여부')),
                ('help_receive', models.CharField(choices=[('learning', '배우기 (스마트폰 사용법, 운동 등)'), ('labor', '일손 (정리, 청소 등)'), ('care', '돌봄 (동행, 말벗 등)'), ('other', '기타')], max_length=20, verbose_name='받고 싶은 도움')),
                ('help_receive_other', models.CharField(blank=True, max_length=200, null=True, verbose_name='받고 싶은 도움 (기타 내용)')),
                ('help_give', models.CharField(choices=[('teaching', '가르치기 (스마트폰 사용법, 운동 등)'), ('labor', '일손 돕기 (정리, 청소, 수선 등)'), ('care', '돌봄 (동행, 말벗 등)'), ('other', '기타')], max_length=20, verbose_name='줄 수 있는 도움')),
                ('help_give_other', models.CharField(blank=True, max_length=200, null=True, verbose_name='줄 수 있는 도움 (기타 내용)')),
                ('time_commitment', models.CharField(choices=[('3months', '3개월에 1~2시간 정도'), ('1month', '1개월에 1~2시간 정도'), ('1week', '1주일에 1~2시간 정도'), ('other', '기타')], max_length=20, verbose_name='참여 가능 시간')),
                ('time_commitment_other', models.CharField(blank=True, max_length=200, null=True, verbose_name='참여 가능 시간 (기타 내용)')),
                ('support_network', models.CharField(choices=[('0', '없다'), ('1', '1명'), ('2', '2명'), ('3+', '3명 이상')], max_length=2, verbose_name='도움 요청 가능한 사람 수')),
                ('participation_type', models.CharField(choices=[('regular', '정기 모임(소모임 형태)'), ('ondemand', '필요할 때만 참여(개별 교류)'), ('online', '온라인 중심 교류(앱, 단톡방 등)'), ('unsure', '아직 잘 모르겠다')], max_length=20, verbose_name='선호하는 참여 형태')),
                ('expectation', models.CharField(choices=[('meeting', '새로운 사람들과의 만남'), ('support', '도움이 필요할 때 안심'), ('sharing', '나의 재능을 나눌 수 있음'), ('community', '지역 공동체의 따뜻한 분위기'), ('other', '기타')], max_length=20, verbose_name='가장 기대되는 점')),
                ('expectation_other', models.CharField(blank=True, max_length=200, null=True, verbose_name='기대되는 점 (기타 내용)')),
                ('age_group', models.CharField(choices=[('under30', '30세 미만'), ('30-50', '30세 이상 ~ 50세 미만'), ('50-70', '50세 이상 ~ 70세 미만'), ('over70', '70세 이상')], max_length=10, verbose_name='연령대')),
                ('gender', models.CharField(choices=[('male', '남성'), ('female', '여성')], max_length=10, verbose_name='성별')),
                ('residence', models.CharField(choices=[('jeongneung3', '정릉3동'), ('other', '그 외 지역')], max_length=20, verbose_name='거주지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
            ],
            options={
                'verbose_name': '시간은행 설문조사',
                'verbose_name_plural': '시간은행 설문조사 목록',
                'db_table': 'timebank_survey',
                'ordering': ['-created_at'],
            },
        ),
    ]
